using System.Text;
using Microsoft.CodeAnalysis;
using static Waffle.WaffleSyntax;

namespace Iutq.Waffle.Generator;

/// <summary>
///     Renders the frozen query kernels. Waffle drives every repetitive loop:
///     LUT initializer entries, blend entries, event arrays, per-track sample
///     methods and per-partition class emission. Values that need positional
///     alignment are pre-flattened into strings and iterated with ForEach
///     (Waffle's IntProxy index is deferred and cannot index arrays).
/// </summary>
internal static class Emitter
{
    public static void Emit(SourceInfo source, SourceProductionContext context)
    {
        foreach (var partition in source.Partitions)
        {
            foreach (var track in partition.Tracks)
                PrepareTrack(track, partition.Duration);
        }

        var partitionCode = source.Partitions.Select(RenderPartition).ToList();

        var file = Render($$"""
            // <auto-generated by Iutq.Waffle.Generator (Waffle 1.0.1) for {{source.OriginalName}}.iutq />
            using System;
            using System.Runtime.CompilerServices;
            using System.Runtime.InteropServices;
            using Iutq.Core.Primitives;
            using Iutq.Core.Querying;
            using Iutq.Core.Storage;

            namespace Iutq.Frozen.{{source.SanitizedName}};

            [StructLayout(LayoutKind.Sequential, Pack = 4)]
            public readonly struct BlendEntry
            {
                public readonly ushort A;
                public readonly ushort B;
                public readonly float WeightA;

                public BlendEntry(ushort a, ushort b, float weightA)
                {
                    A = a;
                    B = b;
                    WeightA = weightA;
                }
            }

            [StructLayout(LayoutKind.Sequential, Pack = 4)]
            public readonly struct FrozenEvent
            {
                public readonly ushort OffsetA;
                public readonly ushort OffsetB;
                public readonly ushort Tick;
                public readonly float Factor;
                public readonly byte Track;
                public readonly byte Kind;

                public FrozenEvent(ushort offsetA, ushort offsetB, ushort tick, float factor, byte track, byte kind)
                {
                    OffsetA = offsetA;
                    OffsetB = offsetB;
                    Tick = tick;
                    Factor = factor;
                    Track = track;
                    Kind = kind;
                }
            }

            /// <summary>Compile-time frozen database: {{source.OriginalName}}.iutq ({{source.ArenaUnits}} payload units, FNV 0x{{source.PayloadHash.ToString("X8")}}).</summary>
            public static unsafe class FrozenDb
            {
                public const int ArenaOffset = {{source.ArenaOffset}};

                public static readonly string BlobBase64 = "{{source.Base64}}";

                public static readonly byte* Arena;

                static FrozenDb()
                {
                    var bytes = Convert.FromBase64String(BlobBase64);
                    var pinned = GC.AllocateUninitializedArray<byte>(bytes.Length, true);
                    bytes.AsSpan().CopyTo(pinned);

                    fixed (byte* p = pinned)
                    {
                        Arena = p + ArenaOffset;
                    }
                }

                public static ref readonly TClip Payload<TClip>(int unitOffset)
                    where TClip : unmanaged
                    => ref Unsafe.As<byte, TClip>(ref Unsafe.AsRef<byte>(Arena + unitOffset * 4));

                internal static long FloorDiv(long value, long divisor)
                {
                    var quotient = value / divisor;
                    return value >= 0 || quotient * divisor == value ? quotient : quotient - 1;
                }
            }

            {{ForEach(partitionCode, out var pcode)}}
            {{pcode}}

            {{End}}
            """);

        context.AddSource($"{source.SanitizedName}.Frozen.g.cs", file);
    }

    /// <summary>Builds LUT rows / binary bodies once per track before rendering.</summary>
    private static void PrepareTrack(TrackInfo track, int duration)
    {
        switch (track.Strategy)
        {
            case LookupStrategyKind.Dense8:
            {
                var rows = new string[duration];

                for (var tick = 0; tick < duration; tick++)
                {
                    var offset = FindActive(track.LaneA, tick);
                    rows[tick] = offset is null ? "255" : offset.Offset.ToString();
                }

                track.LutRows = rows;
                break;
            }

            case LookupStrategyKind.Dense16:
            {
                var rows = new string[duration];

                for (var tick = 0; tick < duration; tick++)
                {
                    var offset = FindActive(track.LaneA, tick);
                    rows[tick] = offset is null ? "65535" : offset.Offset.ToString();
                }

                track.LutRows = rows;
                break;
            }

            case LookupStrategyKind.BlendLut:
            {
                var entries = new string[duration];

                for (var tick = 0; tick < duration; tick++)
                {
                    var laneA = FindActive(track.LaneA, tick);
                    var laneB = FindActive(track.LaneB, tick);

                    if (laneA is not null && laneB is not null)
                    {
                        var pair = track.Pairs.Single(p => p.BlendStart <= tick && tick < p.BlendEnd);
                        var factorText = BlobParser.BlendFactorLiteral(tick, pair.BlendStart, pair.BlendEnd);
                        var factor = ParseFloat(factorText);
                        // Replicate runtime exactly: weightB = LaneBFirst ? factor : 1f - factor; weightA = 1f - weightB.
                        var weightB = pair.LaneBFirst ? factor : 1f - factor;
                        entries[tick] = $"new BlendEntry({laneA.Offset}, {laneB.Offset}, {FormatFloat(1f - weightB)})";
                    }
                    else if (laneA is not null)
                    {
                        entries[tick] = $"new BlendEntry({laneA.Offset}, 65535, 1f)";
                    }
                    else if (laneB is not null)
                    {
                        entries[tick] = $"new BlendEntry(65535, {laneB.Offset}, 1f)";
                    }
                    else
                    {
                        entries[tick] = "new BlendEntry(65535, 65535, 1f)";
                    }
                }

                track.BlendEntries = entries;
                break;
            }

            case LookupStrategyKind.Binary:
            {
                var sb = new StringBuilder();
                AppendBinaryTree(sb, track.LaneA, 0, track.LaneA.Count, 2, track.Index);
                track.BinaryBody = sb.ToString();
                break;
            }
        }
    }

    private static float ParseFloat(string literal) =>
        float.Parse(literal.TrimEnd('f'), System.Globalization.CultureInfo.InvariantCulture);

    private static string FormatFloat(float value) => BlobParser.FormatFloat(value);

    private static ClipInfo? FindActive(List<ClipInfo> lane, int tick)
    {
        foreach (var clip in lane)
            if (tick >= clip.Start && tick < clip.Start + clip.Len)
                return clip;

        return null;
    }

    private static void AppendBinaryTree(StringBuilder sb, List<ClipInfo> clips, int lo, int hi, int indent, int trackIndex)
    {
        var pad = new string(' ', indent);

        if (lo >= hi)
        {
            sb.Append(pad).Append("return;\n");
            return;
        }

        if (hi - lo == 1)
        {
            var clip = clips[lo];
            sb.Append(pad).Append($"if ((uint)(tick - {clip.Start}) < {clip.Len}u)\n");
            sb.Append(pad).Append("{\n");
            sb.Append(pad).Append($"    visitor.Sample(Tracks[{trackIndex}], FrozenDb.Payload<TClip>({clip.Offset}), 1f);\n");
            sb.Append(pad).Append("}\n");
            sb.Append(pad).Append("return;\n");
            return;
        }

        var mid = (lo + hi) >> 1;
        var pivot = clips[mid];

        sb.Append(pad).Append($"if (tick < {pivot.Start})\n");
        sb.Append(pad).Append("{\n");
        AppendBinaryTree(sb, clips, lo, mid, indent + 4, trackIndex);
        sb.Append(pad).Append("}\n");
        sb.Append(pad).Append($"else if ((uint)(tick - {pivot.Start}) >= {pivot.Len}u)\n");
        sb.Append(pad).Append("{\n");
        AppendBinaryTree(sb, clips, mid + 1, hi, indent + 4, trackIndex);
        sb.Append(pad).Append("}\n");
        sb.Append(pad).Append("else\n");
        sb.Append(pad).Append("{\n");
        sb.Append(pad).Append($"    visitor.Sample(Tracks[{trackIndex}], FrozenDb.Payload<TClip>({pivot.Offset}), 1f);\n");
        sb.Append(pad).Append("    return;\n");
        sb.Append(pad).Append("}\n");
    }

    private static string RenderTrackSample(TrackInfo track)
    {
        switch (track.Strategy)
        {
            case LookupStrategyKind.Tiny:
            {
                var clipChecks = track.LaneA
                    .Select(c => string.Join("\n",
                        $"                if ((uint)(tick - {c.Start}) < {c.Len}u)",
                        "                {",
                        $"                    visitor.Sample(Tracks[{track.Index}], FrozenDb.Payload<TClip>({c.Offset}), 1f);",
                        "                    return;",
                        "                }"))
                        .ToList();

                return Render($$"""
                        // Track {{track.Index}}: {{track.ModeName}}, Tiny comparison chain ({{track.ClipCount}} clips).
                        public static void Sample{{track.Index}}<TClip, TVisitor>(int tick, ref TVisitor visitor)
                            where TClip : unmanaged
                            where TVisitor : struct, IClipSampleVisitor<TClip>
                        {
                        {{ForEach(clipChecks, out var check)}}
                        {{check}}

                        {{End}}            }
                        """);
            }

            case LookupStrategyKind.Dense8:
            case LookupStrategyKind.Dense16:
            {
                var rows = track.LutRows;
                var arrayType = track.Strategy == LookupStrategyKind.Dense8 ? "byte" : "ushort";
                var sentinel = track.Strategy == LookupStrategyKind.Dense8 ? "255" : "65535";
                var spanType = $"ReadOnlySpan<{arrayType}>";

                return Render($$"""
                        // Track {{track.Index}}: {{track.ModeName}}, {{track.StrategyName}} ({{rows.Length}} entries).
                        private static readonly {{arrayType}}[] ClipLut{{track.Index}} =
                        {
                            {{ForEach(rows, out var row)}}{{row}}, {{End}}
                        };

                        public static void Sample{{track.Index}}<TClip, TVisitor>(int tick, ref TVisitor visitor)
                            where TClip : unmanaged
                            where TVisitor : struct, IClipSampleVisitor<TClip>
                        {
                            var offset = Unsafe.Add(ref MemoryMarshal.GetReference(({{spanType}})ClipLut{{track.Index}}), (nint)(uint)tick);

                            if (offset != {{sentinel}})
                            {
                                visitor.Sample(Tracks[{{track.Index}}], FrozenDb.Payload<TClip>(offset), 1f);
                            }
                        }
                        """);
            }

            case LookupStrategyKind.BlendLut:
            {
                var entries = track.BlendEntries;

                return Render($$"""
                        // Track {{track.Index}}: {{track.ModeName}}, {{track.StrategyName}} ({{entries.Length}} entries, weightA baked).
                        private static readonly BlendEntry[] BlendLut{{track.Index}} =
                        {
                            {{ForEach(entries, out var entry)}}{{entry}}, {{End}}
                        };

                        public static void Sample{{track.Index}}<TClip, TVisitor>(int tick, ref TVisitor visitor)
                            where TClip : unmanaged
                            where TVisitor : struct, IClipSampleVisitor<TClip>
                        {
                            var e = Unsafe.Add(ref MemoryMarshal.GetReference((ReadOnlySpan<BlendEntry>)BlendLut{{track.Index}}), (nint)(uint)tick);

                            if (e.A == 65535)
                            {
                                if (e.B == 65535)
                                {
                                    return;
                                }

                                visitor.Sample(Tracks[{{track.Index}}], FrozenDb.Payload<TClip>(e.B), 1f);
                                return;
                            }

                            if (e.B == 65535)
                            {
                                visitor.Sample(Tracks[{{track.Index}}], FrozenDb.Payload<TClip>(e.A), 1f);
                                return;
                            }

                            visitor.Sample(Tracks[{{track.Index}}], FrozenDb.Payload<TClip>(e.A), e.WeightA);
                            visitor.Sample(Tracks[{{track.Index}}], FrozenDb.Payload<TClip>(e.B), 1f - e.WeightA);
                        }
                        """);
            }

            default: // Binary
            {
                var body = track.BinaryBody;

                return Render($$"""
                        // Track {{track.Index}}: {{track.ModeName}}, {{track.StrategyName}}.
                        public static void Sample{{track.Index}}<TClip, TVisitor>(int tick, ref TVisitor visitor)
                            where TClip : unmanaged
                            where TVisitor : struct, IClipSampleVisitor<TClip>
                        {
                        {{body}}            }
                        """);
            }
        }
    }

    private static string RenderPartition(PartitionInfo p)
    {
        var sampleBodies = p.Tracks.Select(RenderTrackSample).ToList();
        var trackInstances = p.Tracks.Select(t => $"new TrackInstance({t.Binding}, {t.TemplateId})").ToList();
        var tickStartText = p.TickStart.Select(v => v.ToString()).ToArray();
        var eventTexts = Enumerable.Range(0, p.EventCount)
            .Select(i => $"new FrozenEvent({p.EvOffA[i]}, {p.EvOffB[i]}, {p.EvTick[i]}, {p.EvFactor[i]}, {p.EvTrack[i]}, {p.EvKind[i]})")
            .ToList();
        var strategySummary = string.Join("; ", p.Tracks.Select(t => $"track {t.Index}: {t.StrategyName}"));
        var loopText = p.Loop ? "true" : "false";

        return Render($$"""
                // Timeline index {{p.TimelineIndex}}: key 0x{{p.TimelineKey.ToString("X16")}}, duration {{p.Duration}}{{If(p.Loop)}}, loop{{End}}.
                // Type slot {{p.TypeSlot}}: key 0x{{p.TypeKey.ToString("X16")}}, {{p.PayloadSize}}-byte payloads.
                // Strategies: {{strategySummary}}
                public static unsafe class {{p.ClassName}}
                {
                    public const int Duration = {{p.Duration}};
                    public static readonly bool Loop = {{loopText}};
                    public const ulong TimelineKey = 0x{{p.TimelineKey.ToString("X16")}}UL;
                    public const ulong TypeKey = 0x{{p.TypeKey.ToString("X16")}}UL;

                    private static readonly TrackInstance[] Tracks =
                    {
                        {{ForEach(trackInstances, out var instance)}}{{instance}}, {{End}}
                    };

                {{ForEach(sampleBodies, out var body)}}
                {{body}}

                {{End}}
                    // Transition tables: {{p.EventCount}} merged events (tick-major order), prefix table of {{p.TickStart.Length}} entries.
                    private static readonly ushort[] TickStart =
                    {
                        {{ForEach(tickStartText, out var ts)}}{{ts}}, {{End}}
                    };

                    private static readonly FrozenEvent[] Events =
                    {
                        {{ForEach(eventTexts, out var ev)}}{{ev}}, {{End}}
                    };

                    public static long Traverse<TClip, TVisitor>(in TimelineSpan span, ref TVisitor visitor)
                        where TClip : unmanaged
                        where TVisitor : struct, IClipTransitionVisitor<TClip>
                    {
                        if (span.CurrentRawTick == span.PreviousRawTick)
                        {
                            return 0;
                        }

                        return span.CurrentRawTick > span.PreviousRawTick
                            ? TraverseCore<TClip, TVisitor>(span.PreviousRawTick + 1, span.CurrentRawTick, TimelineDirection.Forward, ref visitor)
                            : TraverseCore<TClip, TVisitor>(span.CurrentRawTick, span.PreviousRawTick - 1, TimelineDirection.Reverse, ref visitor);
                    }

                    private static long TraverseCore<TClip, TVisitor>(long low, long high, TimelineDirection direction, ref TVisitor visitor)
                        where TClip : unmanaged
                        where TVisitor : struct, IClipTransitionVisitor<TClip>
                    {
                        long duration = Duration;

                        if (!Loop)
                        {
                            var lo = Math.Max(low, 0);
                            var hi = Math.Min(high, duration - 1);
                            return lo > hi ? 0 : EmitRange<TClip, TVisitor>((int)lo, (int)hi, 0, direction, ref visitor);
                        }

                        if ((ulong)low < (ulong)duration && (ulong)high < (ulong)duration)
                        {
                            return EmitRange<TClip, TVisitor>((int)low, (int)high, 0, direction, ref visitor);
                        }

                        var lowCycle = FrozenDb.FloorDiv(low, duration);
                        var highCycle = FrozenDb.FloorDiv(high, duration);

                        if (lowCycle == highCycle)
                        {
                            return EmitRange<TClip, TVisitor>(
                                (int)(low - lowCycle * duration), (int)(high - highCycle * duration), lowCycle, direction, ref visitor);
                        }

                        long total;

                        if (direction == TimelineDirection.Forward)
                        {
                            total = EmitRange<TClip, TVisitor>((int)(low - lowCycle * duration), (int)(duration - 1), lowCycle, direction, ref visitor);

                            for (var cycle = lowCycle + 1; cycle < highCycle; cycle++)
                            {
                                total += EmitRange<TClip, TVisitor>(0, (int)(duration - 1), cycle, direction, ref visitor);
                            }

                            total += EmitRange<TClip, TVisitor>(0, (int)(high - highCycle * duration), highCycle, direction, ref visitor);
                        }
                        else
                        {
                            total = EmitRange<TClip, TVisitor>(0, (int)(high - highCycle * duration), highCycle, direction, ref visitor);

                            for (var cycle = highCycle - 1; cycle > lowCycle; cycle--)
                            {
                                total += EmitRange<TClip, TVisitor>(0, (int)(duration - 1), cycle, direction, ref visitor);
                            }

                            total += EmitRange<TClip, TVisitor>((int)(low - lowCycle * duration), (int)(duration - 1), lowCycle, direction, ref visitor);
                        }

                        return total;
                    }

                    private static long EmitRange<TClip, TVisitor>(int loLocal, int hiLocal, long cycle, TimelineDirection direction, ref TVisitor visitor)
                        where TClip : unmanaged
                        where TVisitor : struct, IClipTransitionVisitor<TClip>
                    {
                        var start = Unsafe.Add(ref MemoryMarshal.GetReference((ReadOnlySpan<ushort>)TickStart), (nint)(uint)loLocal);
                        var end = Unsafe.Add(ref MemoryMarshal.GetReference((ReadOnlySpan<ushort>)TickStart), (nint)(uint)hiLocal + 1);
                        long emitted = 0;

                        if (direction == TimelineDirection.Forward)
                        {
                            for (var i = start; i < end; i++)
                            {
                                emitted += Emit<TClip, TVisitor>(i, cycle, direction, ref visitor);
                            }
                        }
                        else
                        {
                            for (var i = end - 1; i >= start; i--)
                            {
                                emitted += Emit<TClip, TVisitor>(i, cycle, direction, ref visitor);
                            }
                        }

                        return emitted;
                    }

                    private static long Emit<TClip, TVisitor>(int eventIndex, long cycle, TimelineDirection direction, ref TVisitor visitor)
                        where TClip : unmanaged
                        where TVisitor : struct, IClipTransitionVisitor<TClip>
                    {
                        var e = Unsafe.Add(ref MemoryMarshal.GetReference((ReadOnlySpan<FrozenEvent>)Events), (nint)(uint)eventIndex);
                        var globalTick = checked(cycle * (long)Duration + e.Tick);

                        switch (e.Kind)
                        {
                            case 0: // ClipStart
                                visitor.OnClipTransition(
                                    Tracks[e.Track],
                                    new ClipTransition(globalTick, e.Tick, direction,
                                        direction == TimelineDirection.Forward ? ClipPhase.Enter : ClipPhase.Exit, e.OffsetA),
                                    in FrozenDb.Payload<TClip>(e.OffsetA));
                                return 1;
                            case 5: // ClipEnd
                                visitor.OnClipTransition(
                                    Tracks[e.Track],
                                    new ClipTransition(globalTick, e.Tick, direction,
                                        direction == TimelineDirection.Forward ? ClipPhase.Exit : ClipPhase.Enter, e.OffsetA),
                                    in FrozenDb.Payload<TClip>(e.OffsetA));
                                return 1;
                            case 2: // ClipInstant
                                visitor.OnClipTransition(
                                    Tracks[e.Track],
                                    new ClipTransition(globalTick, e.Tick, direction, ClipPhase.Enter, e.OffsetA),
                                    in FrozenDb.Payload<TClip>(e.OffsetA));
                                return 1;
                            case 3: // BlendInstant
                                visitor.OnBlendTransition(
                                    Tracks[e.Track],
                                    new BlendTransition(globalTick, e.Tick, direction, BlendPhase.Enter, e.OffsetA, e.OffsetB, e.Factor),
                                    in FrozenDb.Payload<TClip>(e.OffsetA), FrozenDb.Payload<TClip>(e.OffsetB));
                                return 1;
                            default: // BlendStart (1) / BlendEnd (4)
                                var phase = (e.Kind == 1) == (direction == TimelineDirection.Forward)
                                    ? BlendPhase.Enter
                                    : BlendPhase.Exit;
                                visitor.OnBlendTransition(
                                    Tracks[e.Track],
                                    new BlendTransition(globalTick, e.Tick, direction, phase, e.OffsetA, e.OffsetB, e.Factor),
                                    in FrozenDb.Payload<TClip>(e.OffsetA), FrozenDb.Payload<TClip>(e.OffsetB));
                                return 1;
                        }
                    }
                }
                """);
    }
}
